/**
 * Mappa chiave interna → intestazione esatta del foglio "Immobili" (template
 * v3). Un solo punto di verità: se il template cambia, si cambia solo qui.
 */
export const COLUMNS = {
  id: 'ID',
  slug: 'Slug',
  title: 'Titolo',
  visible: 'Visibile',
  status: 'Stato',
  transaction: 'Contratto',
  propertyType: 'Tipologia',
  publicationDate: 'Data pubblicazione',
  featuredHome: 'Featured home',
  homeOrder: 'Ordine home',
  usaf: 'USAF',
  newDevelopment: 'Nuova realizzazione',
  projectName: 'Nome progetto',
  comune: 'Comune',
  provincia: 'Provincia',
  zona: 'Zona / Frazione',
  address: 'Indirizzo (opzionale)',
  showAddress: 'Mostra indirizzo',
  price: 'Prezzo',
  priceOnRequest: 'Prezzo su richiesta',
  monthlyRent: 'Canone mensile',
  monthlyCondoFees: 'Spese condominiali / mese',
  surface: 'Superficie commerciale m²',
  bedrooms: 'Camere',
  bathrooms: 'Bagni',
  floor: 'Piano',
  buildingFloors: 'Piani edificio',
  constructionYear: 'Anno costruzione',
  energyClass: 'Classe energetica',
  ipe: 'IPE / EPgl,nren',
  garage: 'Garage / Box',
  garageType: 'Tipo garage / box',
  parkingSpot: 'Posto auto',
  parkingSpotCovered: 'Posto auto coperto',
  garden: 'Giardino',
  gardenSurface: 'Superficie giardino m²',
  terrace: 'Terrazzo',
  terraceSurface: 'Superficie terrazzo m²',
  balcony: 'Balcone',
  porch: 'Porticato',
  porchSurface: 'Superficie porticato m²',
  elevator: 'Ascensore',
  cellar: 'Cantina',
  airConditioning: 'Climatizzazione',
  furnished: 'Arredato',
  photovoltaic: 'Fotovoltaico',
  pool: 'Piscina',
  heating: 'Riscaldamento',
  otherFeatures: 'Altre caratteristiche',
  shortDescription: 'Descrizione breve',
  description: 'Descrizione completa',
  videoUrl: 'Video / Virtual tour URL',
  metaTitle: 'Meta title',
  metaDescription: 'Meta description',
};

/** Colonne trattate come booleane SI/NO/0. */
export const BOOLEAN_COLUMNS = [
  'visible',
  'featuredHome',
  'usaf',
  'newDevelopment',
  'showAddress',
  'priceOnRequest',
  'garage',
  'parkingSpot',
  'parkingSpotCovered',
  'garden',
  'terrace',
  'balcony',
  'porch',
  'elevator',
  'cellar',
  'airConditioning',
  'furnished',
  'photovoltaic',
  'pool',
];

/** Il foglio pubblico da leggere — gli altri (Liste, Esempio, Istruzioni) non sono dataset. */
export const SHEET_NAME = 'Immobili';
